name: "fixtures-test"

version: 1.0.0

client:
  organization: Org1

  logging:
    level: info

  cryptoconfig:
    path: /home/alex/go/src/github.com/Aguaments/network/fixtures/crypto-config

  credentialStore:
    path: "/tmp/state-store"

    cryptoStore:
      # Specific to the underlying KeyValueStore that backs the crypto key store.
      path: /tmp/msp

  BCCSP:
    security:
      enabled: true
      default:
        provider: "SW"
      hashAlgorithm: "SHA2"
      softVerify: true
      level: 256

  tlsCerts:
    # [Optional]. Use system certificate pool when connecting to peers, orderers (for negotiating TLS) Default: false
    systemCertPool: true

    # [Optional]. Client key and cert for TLS handshake with peers and orderers
    client:
      key:
        path: /home/alex/go/src/github.com/Aguaments/network/fixtures/crypto-config/peerOrganizations/org1.com/users/Admin@org1.com/tls/client.key
      cert:
        path: /home/alex/go/src/github.com/Aguaments/network/fixtures/crypto-config/peerOrganizations/org1.com/users/Admin@org1.com/tls/client.crt

channels:
  # multi-org test channel
  channel1:
    peers:
      peer0.org1.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      peer0.org2.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      peer0.org3.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      peer0.org4.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

    policies:
      queryChannelConfig:
        minResponses: 1
        maxTargets: 1
        retryOpts:
          attempts: 5
          initialBackoff: 500ms
          maxBackoff: 5s
          backoffFactor: 2.0

    discovery:
      #[Optional] discovery info will be retrieved for these number of random targets
      maxTargets: 2
      #[Optional] retry options for retrieving discovery info
      retryOpts:
        #[Optional] number of retry attempts
        attempts: 4
        #[Optional] the back off interval for the first retry attempt
        initialBackoff: 500ms
        #[Optional] the maximum back off interval for any retry attempt
        maxBackoff: 5s
        #[Optional] he factor by which the initial back off period is exponentially incremented
        backoffFactor: 2.0
#
# list of participating organizations in this nettestwork
#
organizations:
  Org1:
    mspid: Org1MSP

    # This org's MSP store (absolute path or relative to client.cryptoconfig)
    cryptoPath: /home/alex/go/src/github.com/Aguaments/network/fixtures/crypto-config/peerOrganizations/org1.com/users/Admin@org1.com/msp

    peers:
      - peer0.org1.com

  Org2:
    mspid: Org2MSP

    # This org's MSP store (absolute path or relative to client.cryptoconfig)
    cryptoPath: /home/alex/go/src/github.com/Aguaments/network/fixtures/crypto-config/peerOrganizations/org2.com/users/Admin@org2.com/msp

    peers:
      - peer0.org2.com

  Org3:
    mspid: Org3MSP

    # This org's MSP store (absolute path or relative to client.cryptoconfig)
    cryptoPath: /home/alex/go/src/github.com/Aguaments/network/fixtures/crypto-config/peerOrganizations/org3.com/users/Admin@org3.com/msp

    peers:
      - peer0.org3.com

  Org4:
    mspid: Org4MSP

    # This org's MSP store (absolute path or relative to client.cryptoconfig)
    cryptoPath: /home/alex/go/src/github.com/Aguaments/network/fixtures/crypto-config/peerOrganizations/org4.com/users/Admin@org4.com/msp

    peers:
      - peer0.org4.com

    # [Optional]. Certificate Authorities issue certificates for identification purposes in a Fabric based
    # nettestwork. Typically certificates provisioning is done in a separate process outside of the
    # runtime nettestwork. Fabric-CA is a special certificate authority that provides a REST APIs for
    # dynamic certificate management (enroll, revoke, re-enroll). The following section is only for
    # Fabric-CA servers.

    # the profile will contain public information about organizations other than the one it belongs to.
    # These are necessary information to make transaction lifecycles testwork, including MSP IDs and
    # peers with a public URL to send transaction proposals. The file will not contain private
    # information reserved for members of the organization, such as admin key and certificate,
    # fabric-ca registrar enroll ID and secret, etc.
    #  org1:
    #    mspid: org1MSP

    # This org's MSP store (absolute path or relative to client.cryptoconfig)
  #    cryptoPath:  peerOrganizations/org1.example.com/users/{username}@org1.example.com/msp

  #    peers:
  #      - peer0.org1.example.com

  # Orderer Org name
  OrdererOrg:
    # Membership Service Provider ID for this organization
    mspID: OrdererMSP

    # Needed to load users crypto keys and certs for this org (absolute path or relative to global crypto path, DEV mode)
    cryptoPath: /home/alex/go/src/github.com/Aguaments/network/fixtures/crypto-config/ordererOrganizations/orderer.com/users/Admin@orderer.com/msp

#
# List of orderers to send transaction and channel create/update requests to. For the time
# being only one orderer is needed. If more than one is defined, which one get used by the
# SDK is implementation specific. Consult each SDK's documentation for its handling of orderers.
#
orderers:
  orderer0.orderer.com:
    # [Optional] Default: Infer from hostname
    url: orderer0.orderer.com:5050

    # these are standard properties defined by the gRPC library
    # they will be passed in as-is to gRPC client constructor
    grpcOptions:
      ssl-target-name-override: orderer0.orderer.com
      # These parameters should be set in coordination with the keepalive policy on the server,
      # as incompatible settings can result in closing of connection.
      # When duration of the 'keep-alive-time' is set to 0 or less the keep alive client parameters are disabled
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      # allow-insecure will be taken into consideration if address has no protocol defined, if true then grpc or else grpcs
      allow-insecure: false

    tlsCACerts:
      # Certificate location absolute path
      path: /home/alex/go/src/github.com/Aguaments/network/fixtures/crypto-config/ordererOrganizations/orderer.com/tlsca/tlsca.orderer.com-cert.pem
#
#
#  orderer1.orderer.com:
#    # [Optional] Default: Infer from hostname
#    url: orderer1.orderer.com:6050
#
#    # these are standard properties defined by the gRPC library
#    # they will be passed in as-is to gRPC client constructor
#    grpcOptions:
#      ssl-target-name-override: orderer1.orderer.com
#      # These parameters should be set in coordination with the keepalive policy on the server,
#      # as incompatible settings can result in closing of connection.
#      # When duration of the 'keep-alive-time' is set to 0 or less the keep alive client parameters are disabled
#      keep-alive-time: 0s
#      keep-alive-timeout: 20s
#      keep-alive-permit: false
#      fail-fast: false
#      # allow-insecure will be taken into consideration if address has no protocol defined, if true then grpc or else grpcs
#      allow-insecure: false
#
#    tlsCACerts:
#      # Certificate location absolute path
#      path: /home/alex/go/static/github.com/Aguaments/network/fixtures/crypto-config/ordererOrganizations/orderer.com/tlsca/tlsca.orderer.com-cert.pem
#
#
#  orderer2.orderer.com:
#    # [Optional] Default: Infer from hostname
#    url: orderer2.orderer.com:7050
#
#    # these are standard properties defined by the gRPC library
#    # they will be passed in as-is to gRPC client constructor
#    grpcOptions:
#      ssl-target-name-override: orderer2.orderer.com
#      # These parameters should be set in coordination with the keepalive policy on the server,
#      # as incompatible settings can result in closing of connection.
#      # When duration of the 'keep-alive-time' is set to 0 or less the keep alive client parameters are disabled
#      keep-alive-time: 0s
#      keep-alive-timeout: 20s
#      keep-alive-permit: false
#      fail-fast: false
#      # allow-insecure will be taken into consideration if address has no protocol defined, if true then grpc or else grpcs
#      allow-insecure: false
#
#    tlsCACerts:
#      # Certificate location absolute path
#      path: /home/alex/go/static/github.com/Aguaments/network/fixtures/crypto-config/ordererOrganizations/orderer.com/tlsca/tlsca.orderer.com-cert.pem

#
# List of peers to send various requests to, including endorsement, query
# and event listener registration.
#
peers:
  peer0.org1.com:
    # this URL is used to send endorsement and query requests
    # [Optional] Default: Infer from hostname
    url: peer0.org1.com:7051
    grpcOptions:
      ssl-target-name-override: peer0.org1.com
      # These parameters should be set in coordination with the keepalive policy on the server,
      # as incompatible settings can result in closing of connection.
      # When duration of the 'keep-alive-time' is set to 0 or less the keep alive client parameters are disabled
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      # allow-insecure will be taken into consideration if address has no protocol defined, if true then grpc or else grpcs
      allow-insecure: false
    #grpcOptions:
    #  ssl-target-name-override: peer0.org1.example.com

    tlsCACerts:
      # Certificate location absolute path
      path: /home/alex/go/src/github.com/Aguaments/network/fixtures/crypto-config/peerOrganizations/org1.com/tlsca/tlsca.org1.com-cert.pem

  peer0.org2.com:
    # this URL is used to send endorsement and query requests
    # [Optional] Default: Infer from hostname
    url: peer0.org2.com:8051
    grpcOptions:
      ssl-target-name-override: peer0.org2.com
      # These parameters should be set in coordination with the keepalive policy on the server,
      # as incompatible settings can result in closing of connection.
      # When duration of the 'keep-alive-time' is set to 0 or less the keep alive client parameters are disabled
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      # allow-insecure will be taken into consideration if address has no protocol defined, if true then grpc or else grpcs
      allow-insecure: false
    #grpcOptions:
    #  ssl-target-name-override: peer0.org1.example.com

    tlsCACerts:
      # Certificate location absolute path
      path: /home/alex/go/src/github.com/Aguaments/network/fixtures/crypto-config/peerOrganizations/org2.com/tlsca/tlsca.org2.com-cert.pem

  peer0.org3.com:
    # this URL is used to send endorsement and query requests
    # [Optional] Default: Infer from hostname
    url: peer0.org3.com:9051
    grpcOptions:
      ssl-target-name-override: peer0.org3.com
      # These parameters should be set in coordination with the keepalive policy on the server,
      # as incompatible settings can result in closing of connection.
      # When duration of the 'keep-alive-time' is set to 0 or less the keep alive client parameters are disabled
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      # allow-insecure will be taken into consideration if address has no protocol defined, if true then grpc or else grpcs
      allow-insecure: false
    #grpcOptions:
    #  ssl-target-name-override: peer0.org1.example.com

    tlsCACerts:
      # Certificate location absolute path
      path: /home/alex/go/src/github.com/Aguaments/network/fixtures/crypto-config/peerOrganizations/org3.com/tlsca/tlsca.org3.com-cert.pem

  peer0.org4.com:
    # this URL is used to send endorsement and query requests
    # [Optional] Default: Infer from hostname
    url: peer0.org4.com:10051
    grpcOptions:
      ssl-target-name-override: peer0.org4.com
      # These parameters should be set in coordination with the keepalive policy on the server,
      # as incompatible settings can result in closing of connection.
      # When duration of the 'keep-alive-time' is set to 0 or less the keep alive client parameters are disabled
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      # allow-insecure will be taken into consideration if address has no protocol defined, if true then grpc or else grpcs
      allow-insecure: false
    #grpcOptions:
    #  ssl-target-name-override: peer0.org1.example.com

    tlsCACerts:
      # Certificate location absolute path
      path: /home/alex/go/src/github.com/Aguaments/network/fixtures/crypto-config/peerOrganizations/org4.com/tlsca/tlsca.org4.com-cert.pem
#
# Fabric-CA is a special kind of Certificate Authority provided by Hyperledger Fabric which allows
# certificate management to be done via REST APIs. Application may choose to use a standard
# Certificate Authority instead of Fabric-CA, in which case this section would not be specified.
#
entityMatchers:
  peer:
    - pattern: (\w+).org1.com:(\d+)
      urlSubstitutionExp: ${1}.org1.com:${2}
      sslTargetOverrideUrlSubstitutionExp: ${1}.org1.com
      mappedHost: peer0.org1.com

    - pattern: (\w+).org2.com:(\d+)
      urlSubstitutionExp: ${1}.org2.com:${2}
      sslTargetOverrideUrlSubstitutionExp: ${1}.org2.com
      mappedHost: peer0.org2.com
    
    - pattern: (\w+).org3.com:(\d+)
      urlSubstitutionExp: ${1}.org3.com:${2}
      sslTargetOverrideUrlSubstitutionExp: ${1}.org3.com
      mappedHost: peer0.org3.com

    - pattern: (\w+).org4.com:(\d+)
      urlSubstitutionExp: ${1}.org4.com:${2}
      sslTargetOverrideUrlSubstitutionExp: ${1}.org4.com
      mappedHost: peer0.org4.com

  orderer:
    - pattern: (\w+).orderer.(\w+)
      urlSubstitutionExp: orderer0.orderer.com:5050
      sslTargetOverrideUrlSubstitutionExp: orderer0.orderer.com
      mappedHost: orderer0.orderer.com
#
#    - pattern: (\w+).orderer.(\w+)
#      urlSubstitutionExp: orderer1.orderer.com:6050
#      sslTargetOverrideUrlSubstitutionExp: orderer1.orderer.com
#      mappedHost: orderer1.orderer.com
#
#    - pattern: (\w+).orderer.(\w+)
#      urlSubstitutionExp: orderer2.orderer.com:7050
#      sslTargetOverrideUrlSubstitutionExp: orderer2.orderer.com
#      mappedHost: orderer2.orderer.com